// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkggregkgjfqrocyudan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZ2dyZWdrZ2pmcXJvY3l1ZGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTkzNTYsImV4cCI6MjA3MDIzNTM1Nn0.LBBgnC_LX1d2x287VPEMBf1_IUakiw3FjhDheskq6U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});