name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: npm run build
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Update Android platform
      run: npx cap update android
      
    - name: Sync with Capacitor
      run: npx cap sync android
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: walletflow-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Release APK (if on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload Release APK artifact (if on main branch)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: walletflow-release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 90